server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:travel_planner_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  application:
    name: backend

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}
    routes-api-url: https://routes.googleapis.com/directions/v2:computeRoutes